# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lab_pb2 as lab__pb2


class LabStub(object):
    """The laboratory service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BigSmall = channel.unary_unary(
                '/Lab/BigSmall',
                request_serializer=lab__pb2.LabRequest.SerializeToString,
                response_deserializer=lab__pb2.LabResponse.FromString,
                )


class LabServicer(object):
    """The laboratory service definition.
    """

    def BigSmall(self, request, context):
        """Sends a array and return the biggest and smallest element, and their respective indexes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LabServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BigSmall': grpc.unary_unary_rpc_method_handler(
                    servicer.BigSmall,
                    request_deserializer=lab__pb2.LabRequest.FromString,
                    response_serializer=lab__pb2.LabResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lab', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lab(object):
    """The laboratory service definition.
    """

    @staticmethod
    def BigSmall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lab/BigSmall',
            lab__pb2.LabRequest.SerializeToString,
            lab__pb2.LabResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
