# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlab.proto\"*\n\nLabRequest\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x0c\n\x04size\x18\x02 \x01(\x05\"]\n\x0bLabResponse\x12\x0f\n\x07\x62iggest\x18\x01 \x01(\x02\x12\x14\n\x0c\x62iggestIndex\x18\x02 \x01(\x05\x12\x10\n\x08smallest\x18\x03 \x01(\x02\x12\x15\n\rsmallestIndex\x18\x04 \x01(\x05\x32.\n\x03Lab\x12\'\n\x08\x42igSmall\x12\x0b.LabRequest\x1a\x0c.LabResponse\"\x00\x62\x06proto3')



_LABREQUEST = DESCRIPTOR.message_types_by_name['LabRequest']
_LABRESPONSE = DESCRIPTOR.message_types_by_name['LabResponse']
LabRequest = _reflection.GeneratedProtocolMessageType('LabRequest', (_message.Message,), {
  'DESCRIPTOR' : _LABREQUEST,
  '__module__' : 'lab_pb2'
  # @@protoc_insertion_point(class_scope:LabRequest)
  })
_sym_db.RegisterMessage(LabRequest)

LabResponse = _reflection.GeneratedProtocolMessageType('LabResponse', (_message.Message,), {
  'DESCRIPTOR' : _LABRESPONSE,
  '__module__' : 'lab_pb2'
  # @@protoc_insertion_point(class_scope:LabResponse)
  })
_sym_db.RegisterMessage(LabResponse)

_LAB = DESCRIPTOR.services_by_name['Lab']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABREQUEST._serialized_start=13
  _LABREQUEST._serialized_end=55
  _LABRESPONSE._serialized_start=57
  _LABRESPONSE._serialized_end=150
  _LAB._serialized_start=152
  _LAB._serialized_end=198
# @@protoc_insertion_point(module_scope)
