/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB_H_RPCGEN
#define _LAB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	float v[500000];
	int len;
};
typedef struct operandos operandos;

struct valor {
	float numero;
	int indice;
};
typedef struct valor valor;

#define PROG 55000555
#define VERS 110011

#if defined(__STDC__) || defined(__cplusplus)
#define acharMenor 1
extern  valor * acharmenor_110011(operandos *, CLIENT *);
extern  valor * acharmenor_110011_svc(operandos *, struct svc_req *);
#define acharMaior 2
extern  valor * acharmaior_110011(operandos *, CLIENT *);
extern  valor * acharmaior_110011_svc(operandos *, struct svc_req *);
extern int prog_110011_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define acharMenor 1
extern  valor * acharmenor_110011();
extern  valor * acharmenor_110011_svc();
#define acharMaior 2
extern  valor * acharmaior_110011();
extern  valor * acharmaior_110011_svc();
extern int prog_110011_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);
extern  bool_t xdr_valor (XDR *, valor*);

#else /* K&R C */
extern bool_t xdr_operandos ();
extern bool_t xdr_valor ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAB_H_RPCGEN */
