/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab.h"

#include <stdlib.h>
#include <math.h>

#define TAM 500000

float f_aleat() {
    return (float)rand() / (float)RAND_MAX * TAM;
}

void inicia_vetor(operandos *arg) {
    int i;
    for (i = 0; i < arg->len; i++) {
        arg->v[i] = pow((i - (f_aleat()/2)),2);
        arg->v[i] = sqrt(arg->v[i]);
        // printf("%f\n", vetor[i]);
    }
}

void
prog_110011(char *host)
{
	CLIENT *clnt;
	valor  *result_1;
	valor  *result_2;
	operandos  arg;

	arg.len = TAM;

	inicia_vetor(&arg);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	result_1 = acharmenor_110011(&arg, clnt);
		printf("O menor valor e %f, na posicao %d\n", result_1->numero, result_1->indice);
	if (result_1 == (valor *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = acharmaior_110011(&arg, clnt);
	if (result_2 == (valor *) NULL) {
		clnt_perror (clnt, "call failed");
	}{
		printf("O maior valor e %f, na posicao %d\n", result_2->numero, result_2->indice);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	host = "127.0.0.1";
	
	prog_110011 (host);
	exit (0);
}
