/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab.h"

valor *
acharvalores_110011_svc(operandos *argp, struct svc_req *rqstp)
{
	static valor  result;

	int i;
    result.menor = argp->v[0];
    result.maior = argp->v[0];


    printf("Tamanho do vetor: %d\n", argp->len);

    for (i = 0; i < argp->len; i++)
    {
        if (argp->v[i] < result.menor)
        {
            result.menor = argp->v[i];
            result.indiceMenor = i;
        }
		if (argp->v[i] > result.maior)
        {
            result.maior = argp->v[i];
            result.indiceMaior = i;
        }
    }

	return &result;
}
