/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab.h"
#include <stdlib.h>
#include <math.h>

#define TAM 500000

float f_aleat() {
    return (float)rand() / (float)RAND_MAX * TAM;
}

void inicia_vetor(operandos *arg) {
    int i;
    for (i = 0; i < arg->len; i++) {
        arg->v[i] = pow((i - (f_aleat()/2)),2);
        arg->v[i] = sqrt(arg->v[i]);
        // printf("%f\n", vetor[i]);
    }
}


void
prog_110011(char *host)
{
	CLIENT *clnt;
	valor  *result;
	operandos  arg;

	arg.len = TAM;

	inicia_vetor(&arg);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result = acharvalores_110011(&arg, clnt);
	if (result == (valor *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Indice do maior: %d\n", result->indiceMaior);
	printf("Maior valor: %f\n", result->maior);
	printf("Indice do menor: %d\n", result->indiceMenor);
	printf("Menor valor: %f\n\n", result->menor);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	host = "127.0.0.1";
	prog_110011 (host);
exit (0);
}
