/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "lab.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
acharvalores_110011(operandos *argp, valor *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, acharValores,
		(xdrproc_t) xdr_operandos, (caddr_t) argp,
		(xdrproc_t) xdr_valor, (caddr_t) clnt_res,
		TIMEOUT));
}
