/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab.h"

valor *
acharmenor_110011_svc(operandos *argp, struct svc_req *rqstp)
{
	static valor  result;

	int i;
    result.numero = argp->v[0];

    printf("%d\n", argp->len);

    for (i = 0; i < argp->len; i++)
    {
        if (argp->v[i] < result.numero)
        {
            result.numero = argp->v[i];
            result.indice = i;
        }
    }

	return &result;
}

valor *
acharmaior_110011_svc(operandos *argp, struct svc_req *rqstp)
{
	static valor  result;

	int i;
    result.numero = argp->v[0];

    for (i = 0; i < argp->len; i++)
    {
        if (argp->v[i] > result.numero)
        {
            result.numero = argp->v[i];
            result.indice = i;
        }
    }

	return &result;
}
